version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Uncomment and add your API keys if using LLM features
      #- OPENAI_API_KEY=
      #- GROQ_API_KEY=your_groq_api_key